### ISSUE TITLE
listeningFocusTrap.unlisten is not a function

### ISSUE THREAD

**Issue by iernie** [davidtheclark/focus-trap#11]
Hi

I'm having an issue using this via the focus-trap-react component. My tests fail after updating to version 2 (version 3 of the react component) with the error message

```
TypeError: listeningFocusTrap.unlisten is not a function
```

Probably it is caused by this line https://github.com/davidtheclark/focus-trap/blob/master/index.js#L80. I've tried looking at the code and I cannot see that unlisten is defined anywhere.

**Comment by davidtheclark** [comment]
Should be fixed in focus-trap 2.0.1, focus-trap-react 3.0.1

**Comment by iernie** [comment]
Awesome, thanks!
