### ISSUE TITLE
About case with absence of focusable elements

### ISSUE THREAD

**Issue by vonagam** [davidtheclark/focus-trap#18]
About pull request #13.

There was stated that "I'd rather throw the error; and then if you or others want it silenced, you can use a try-catch to ignore it".

My use case: a popup which may or may not contain focusable elements.
If there is no such element and i use try-catch, then new focusTrap and its event bindings will not be created. User still will have ability to navigate and activate stuff under popup by tab or other means.

I propose to add some option to createOptions, which will determine, to throw an error or to return null from firstFocusNode if there is no focusable element.

**Comment by davidtheclark** [comment]
@vonagam You should make the popup itself focusable. Focus needs to go somewhere.

**Comment by vonagam** [comment]
There is possibility that there will be a focusable elements in popup's content.
If so, i want this element to gain focus.
So i can't use initialFocus option.

**Comment by davidtheclark** [comment]
@vonagam Sorry but I still don't see the validity in not moving focus into the focus trap. Focus needs to enter the focus trap, or it's not a focus trap. There needs to be a focusable element, or it's not a focus trap. If you don't want to add a focusable element every time, whatever logic you use to conditionally insert the focusable element could also determine whether you use a focus trap.

**Comment by vonagam** [comment]
It is focusable trap in a meaning that it does not allow any thing outside of a trap to be focusable.

I use it to write generic popup library and content is passed as argument. I have no way to know about what logic specific site uses to generate it.

A possible solution is to use "tabbable" package, since focus-group depends on it, to see if there is a focusable element, if no, than to set initialFocus to popup itself.

But it is preferably in my view to have specific option in "focus-group", since its dependencies can change and not part of api.

**Comment by vonagam** [comment]
Maybe "fallbackFocus". If this option is present and there is no focusable element in container, than use this one, instead of throwing error.

Do you think that using "tabbable" directly is more desirable than adding new option?

**Comment by davidtheclark** [comment]
`fallbackFocus` is a good idea. You should be able to do that fallback yourself using try-catch: if an error is caught, create a new focusTrap with the fallback focus. Right?

This has come up before, though, so if you're interested in a PR implementing a `fallbackFocus` option, that would be great.

**Comment by vonagam** [comment]
Hm. Yeah, try-catch with setting initialFocus to a popup on catch is a solution that doesn't depend on "tabbable". But it makes code kinda ugly, though.

Ok, i'll try to create pull with `fallbackFocus`.

**Comment by vonagam** [comment]
This issue can be closed now, as pull request was merged.
