### ISSUE TITLE
Scrolling to top when gaining focus

### ISSUE THREAD

**Issue by sam-s4s** [davidtheclark/focus-trap#20]
I have a scrollable div with lots of inputs in it.

When the focus-trap activates, it scrolls to the top. So even if you click on an input at the bottom, and it gains focus, the view is scrolled to the top, and the input with focus is no longer visible.

Other than that, this is working great, so thank you! :D

**Comment by davidtheclark** [comment]
@sam-s4s: This doesn't sound like a problem with this library, but maybe with your particular context. All this library does is set focus, not affect scrolling — except insofar as focus can affect scrolling.

> When the focus-trap activates, it scrolls to the top.

That doesn't happen in the demos, so not sure what's different about your context.

**Comment by sam-s4s** [comment]
Thanks for the quick reply :)

Hmmm, I'm not sure how to fix this problem though!

New information: So when I say "scrolling to the top", I've found out it's actually just scrolling to the first tabbable element in the div.

However, that element was not previously selected, and it not currently selected.

So it's like focus-trap is maybe temporarily giving focus to that element, causing the page to scroll to that location?

(so the fix would be to just never give focus to any elements who should not have focus) ?

**Comment by sam-s4s** [comment]
In narrowing the bug down, it appears to be something to do with initialFocus....

Previously I was not setting it at all, and now when setting initialFocus: true, it is working correctly...

However, it is not actually doing the initialFocus thing hah which is good for what I'm trying to do, however not how it's supposed to behave?

**Comment by davidtheclark** [comment]
> However, what if I don't want it to select anything?

No. This has been discussed in a few prior issues, so I'd look at those. Recently a new option was added for `focusFallback` in case you don't have a focusable element inside the trap.

You should set `initialFocus` to the element that you want to focus. In this case, the input that was clicked.

**Comment by sam-s4s** [comment]
Ah, but they've already clicked it (and the inputs are out of my control and won't have events on them, and there could be a lot)... so really I just want to say "hey tab-trap, don't change the focus at all please".

**Comment by davidtheclark** [comment]
> You should set initialFocus to the element that you want to focus. In this case, the input that was clicked.

Does that not work?

**Comment by davidtheclark** [comment]
The reason I ask ^^ is because this use-case is precisely what `initialFocus` is for. I'm not in inclined to allow focus-trap to not focus *anything* because then users will open a focus-trap without putting focus inside it.

**Comment by sam-s4s** [comment]
> Does that not work?
It would, but it's a complex app, and I don't want to have an extra event on every input just to deal with focus - as this should just happen when the user clicks on an input anyway (default behaviour).

> I'm not in inclined to allow focus-trap to not focus anything because then users will open a focus-trap without putting focus inside it.

When the user clicks on an input that is included in the focus trap, I'm not sure why any action should be taken? ie. they've done something valid... clicked on a input near the bottom... why try to take over an change the focus? This seems like a bad choice, as you're annoying the user and basically saying "I don't care that you've clicked on that item, I'm going to select this other item that you don't want, haha"

Really the best behaviour is to do nothing, and leave the user with the valid choice, surely? (in the case of a direct focus selection)

**Comment by davidtheclark** [comment]
@sam-s4s: focus-trap does not know what's focused, whether an input was clicked, etc. Your app knows that. So your app needs to handle the logic determine when a focus-trap is opened, and what should receive initial focus within the trap. 

If what you want to say is "Every time an `<input>` in this area receives focus, I want to activate a focus-trap with that `<input>` as the point of initial focus", that should be doable via event delegation or `document.activeElement` without too much trouble, without adding "an extra event on every input just to deal with focus".

**Comment by sam-s4s** [comment]
> If what you want to say is "Every time an <input> in this area receives focus, I want to activate a focus-trap with that <input> as the point of initial focus"

My way of thinking is simply that if an input in the area receives focus, I want to activate a focus trap in that area, but that input already _has_ focus, so I don't want focus-trap to set _any_ initialFocus at all, as the focus is currently correct.

I hope that makes sense! :)

**Comment by davidtheclark** [comment]
@sam-s4s: I'm sorry but I'm not sure what else to say here ...

- I'm not interested in allowing the creation of focus-traps without deliberately putting focus inside the trap. This has come up before, and I'm not convinced it's necessary, though I am convinced it would open the door to bad practices.
- I do not think there is any danger in telling focus-trap to put initial focus on an element that already has focus. `alreadyFocusedElement.focus()` shouldn't cause any problems.
- It sounds to me like you should have no trouble telling the focus-trap where to put initial focus, since you're already listening for focus events in order to activate the focus-trap at all. 

If you disagree with that last point and can't figure out how to implement, feel free to post some code. But I can't guess at how it would be impossible since you have `document.activeElement` at your disposal.
