### ISSUE TITLE
Allow `initialFocus` to be false. Or maybe add another property

### ISSUE THREAD

**Issue by galanovnick** [davidtheclark/focus-trap#22]
Is it really necessary setting up the focus when unpausing\activating focus-trap?
I mean if you wanna be sure that focus is inside focus-trap why just don't check for it? And if it's really somewhere outside, focus the initial element.

Potential use case (not counting previous issues):

If you have some modal divs inside your focus-trap that are being rendered outside of focus-trap (hints, popovers etc.) then you have to pause focus-trap every time they are appearing. And you don't want focus to jump from the current position to the initial position every time you are closing popover, hint or whatever.  Of course in case if your popovers/hints have nothing to focus inside.

p.s. sorry for English

**Comment by davidtheclark** [comment]
@galanovnick Did you look at https://github.com/davidtheclark/focus-trap/issues/5 with the exact same issue title? This question has been addressed a few times, so please review the closed issues and compare your request to them.

If you think your use-case has not been addressed, it would help me understand if you'd build a little demo (can do it in a PR) showing the situation that you believe currently does not work well.

**Comment by davidtheclark** [comment]
I think your concerns have been addressed in release 2.2.0. Please open a new issue if not, specifying what behavior is lacking.

**Comment by galanovnick** [comment]
Yeah, it was. The problem caused by React material components, your plugin works just fine.

**Comment by galanovnick** [comment]
Yes, it was. Thanks a lot.
