### ISSUE TITLE
Focus blinking on collapsing of the inner trap

### ISSUE THREAD

**Issue by galanovnick** [davidtheclark/focus-trap#23]
You can see this behavior on the sixth demo. After inner trap collapsing focus goes to the initial item and then to the "activate inner trap" button.
This behavior visible even on such simple implementation. Just imagine some React components with lots of inputs, buttons and focus animations. Looks horrible with this blinking.

**Comment by galanovnick** [comment]
Maybe it makes sense to handle this 'return focus' behavior in the current active trap? Save the last focus when trap paused, and focus it instead on the initial element when unpaused.

'returnFocusOnDeactivate' -> 'returnFocusOnUnpaused'

**Comment by davidtheclark** [comment]
@galanovnick Do you still see that on the latest demo: https://davidtheclark.github.io/focus-trap/demo/? I saw it last night but it seems to me to be fixed with the latest release.

**Comment by galanovnick** [comment]
@davidtheclark yeah, it's just fine with last release. Thanks.
