### ISSUE TITLE
Feature request: ability to disabled initialFocus option

### ISSUE THREAD

**Issue by iandevlin** [davidtheclark/focus-trap#24]
Hi,

I would like to request an option that allows you to disable the call to `initialFocus`, as I have code  that deals with that elsewhere.
Adding an option such as `noInitialFocus` could allow this.

For example in `addListeners`:

```
 if (getNodeForOption('noInitialFocus') === null) {
   tryFocus(firstFocusNode());
}
```

I have created a local copy that does just this which suits my needs. Happy to submit a PR if you think the addition of this feature is worth it.

Thanks for providing this!

**Comment by davidtheclark** [comment]
Hi @iandevlin. Please search through the issues, as this has been discussed numerous times. If you have a new idea to add to the conversations that have occurred, please open a new issue.

**Comment by iandevlin** [comment]
Ah crap, sorry @davidtheclark, not sure why I didn't search first. My apologies.
