### ISSUE TITLE
When the focus trap is deactivated, it doesn't pass the focus back to the original element [Safari, Firefox]

### ISSUE THREAD

**Issue by psimekjr** [davidtheclark/focus-trap#26]
Hello,

I'd be grateful for a help with following issue:

It seems to pass the focus well (when focus trap is deactivated) in Chrome and IE, however, not in Safari and Firefox. 

It is reproducible on the [demo page](http://davidtheclark.github.io/focus-trap/demo/):
1. Click on 'Activate Trap 1' button
2. Click on 'Deactivate Trap 1' button

Expected result is that 'Activate Trap 1' receives focus.

Thank you,
Pavel

**Comment by davidtheclark** [comment]
You're referring to focus being passed back to the trigger when the focus trap closes?/

I see that bug in Safari (not on Firefox).

PR welcome!

**Comment by psimekjr** [comment]
Thank you for the response, David.

I cloned and debugged the code for a little bit. It looks like the issue is with different behaviour of Safari, compared to other browsers. In Safari buttons don't seem to receive focus on click. That's probably the reason why focus-trap receives the whole body as ```nodeFocusedBeforeActivation``` in Safari.

**Comment by davidtheclark** [comment]
@psimekjr If that's how the browser behaves, I'm not sure there's anything we can do. We could add a caveat to the README saying this is the case?
