### ISSUE TITLE
Tab issue in Edge/IE11

### ISSUE THREAD

**Issue by iandevlin** [davidtheclark/focus-trap#29]
I am having an issue on Edge and IE11 where pressing tab is not cycling the focus around the elements in the focus trap as it does in other browsers. It doesn't move focus outside of the focus trap, but remains at the last element. Going back works fine until it gets to the first focusable item in the focus trap and then it won't cycle to the last.

I am just wondering if it is possible that I am doing something wrong for it to do this? As I said, it works fine in Firefox, Chrome, and Safari.

*edit* your demos work fine in Edge so it must be something that I am doing, but I am not sure what.

Thanks!

**Comment by davidtheclark** [comment]
@iandevlin If the demos work fine, but your code is broken ... there's not anything I can do to help debug, right? Please re-open if you have more specific information.

**Comment by iandevlin** [comment]
I know, I was just wondering if you had perhaps you had come across something when you were building focus-trap, hence I asked. It never helps to ask.

**Comment by davidtheclark** [comment]
@iandevlin: Have not, but if there's anything you'd like me to look at I can try to find some time 👍

**Comment by iandevlin** [comment]
@davidtheclark Hi, I found the issue but it is in `tabbable`and is related to SVGs. I have opened a PR: https://github.com/davidtheclark/tabbable/pull/11
