### ISSUE TITLE
Opt out of initial default focus.

### ISSUE THREAD

**Issue by hally9k** [davidtheclark/focus-trap#31]
We have a use case that makes the initial focus of the first element undesirable. Could we add an option to not automatically focus the first tabbable element?

```
initialFocus: null,  // Maybe?
```

Thanks for all the awesome work!

**Comment by davidtheclark** [comment]
Hi, @hally9k. Thanks for the compliment! This conversation about `initialFocus` has already happened multiple times. Quick summary: I still don't think it's a good idea. Please search the closed issues and look through those comments, and if you feel like you have new reasons why this might be necessary, please re-open the issue.

**Comment by hally9k** [comment]
Ok, so Let me try and outline a scenario in which this is a valid use case.

We are working on an app in which information about a person is collected. A person's info is displayed in a modal which requires a focus trap to function nicely. This modal is used to view the person's info as well as being live for editing that person's data. The viewing use case is more frequent than the editing use case. We are aware that focussing the initial input when the user is merely viewing the info opens the door to potential unintentional edits and lose precious info.

Below is a screen shot to illustrate the scenario where a user might only be viewing info but in danger of unintentionally editing it.

![screen shot 2017-04-14 at 7 35 44 pm](https://cloud.githubusercontent.com/assets/3803536/25036974/c0a69248-214a-11e7-946c-ee639202d681.png)

**Comment by davidtheclark** [comment]
@hally9k: I think in this case you should put initial focus on the modal container itself (with a `tabindex` of `-1`). Demo 4 exemplifies this: https://davidtheclark.github.io/focus-trap/demo/

**Comment by hally9k** [comment]
@davidtheclark Thanks for the prompt reply. How would I achieve your suggested solution using your react wrapper?
