### ISSUE TITLE
Feature request: Exclude-Focus

### ISSUE THREAD

**Issue by shaman-apprentice** [davidtheclark/focus-trap#37]
First of all: Thanks for your great work! I really like your ```focus-trap-react``` and ```react-aria-modal```.

When saving a formular, I show an overlay only over the formular, so that the user can still use other elements of the page. Unfortunately he can also tab "behind" the overlay and change something in the formular. Would it be possible to make a _reversed-focus-trap_, which makes it impossible for their children to receive focus / jumps to the next element outside of the _reversed-focus-trap_?

Thanks in advance!

**Comment by davidtheclark** [comment]
Hi @shaman-apprentice. I can definitely see the usefulness of what you describe. However, that sounds like a different project! I don't see enough overlap between the two modes to justify putting them in the same library. So I suggest you build this!
