### ISSUE TITLE
Does not work on elements within a shadow root

### ISSUE THREAD

**Issue by DRiFTy17** [davidtheclark/focus-trap#39]
I am having an issue getting this to work within a native web component that uses shadow DOM. When creating a focus trap on an element inside of a shadow root, an exception is thrown. 

The exception is actually thrown from `tabbable` when it is traversing the parent nodes and comes across the shadow root element and tries to call `getComputedStyle(node)` on it. By adding a check within `tabbable`s `isOff` function to stop traversing when it hits a node of instance `ShadowRoot` everything appears to work correctly until the tab key is pressed. I can report this in the `tabbable` repository.

Now on to the issue in `focus-trap`. Events that originate from within the shadow dom have their `target` set to the host custom element. This causes a problem when `focus-trap` is checking for the element within its tabbable elements collection. It can be fixed by using the first element in `e.composedPath()` to get the target instead since that will work in both light and shadow dom scenarios.

Anywhere that `e.target` is being used, something like `var target = e.composedPath()[0];` would have to be added, and then use that `target` variable in place of `e.target`.

I wanted to bring this up to you, and see if it's something that is known, or if you had any other thoughts or workarounds. I can create a PR for this as well if you'd like since I've got it working in my local environment.

**Comment by DRiFTy17** [comment]
Another issue I have just come across is elements that are projected using `<slot>` are not picked up in the tab order and therefore cannot be tabbed to. Those DOM trees are not traversed because they live in the light DOM and are just rendered in the slot location within the shadow dom. This also has to do with `tabbable` and it would have to be updated to find any children that are slot elements, and traverse the value returned from each `[slotNode].assignedNodes()` call.

**Comment by davidtheclark** [comment]
@DRiFTy17: I'm open to PRs fixing these libraries for usage with the shadow DOM. I am not currently using web components and don't think I will be for some time, so I won't lead the way here. Sounds like you have some promising ideas 👍

**Comment by DRiFTy17** [comment]
@davidtheclark Okay let me see what I can put together, and I'll try to work out the various issues to get this supported. I'll submit the PRs when I get things complete.

**Comment by davidtheclark** [comment]
With v3 (involving some changes to Tabbable) you should be able to include shadow DOM nodes or iframes or whatever *in the middle* of the focus-trap. Things will get weird if you include those things as the first or last tabbable nodes in the trap. This caveat is now documented in the readme.

So I'm going to close this issue. If anybody comes up with implementation changes that might rid us of that caveat, please open a new issue or PR.
