### ISSUE TITLE
Allow to interact on some outside elements

### ISSUE THREAD

**Issue by gejgalis** [davidtheclark/focus-trap#42]
I'm having an issue using focus-trap with KendoUI and pickers components like Date Picker. When Kendo Date Picker is placed inside trapped container, then I want to open the picker and click inside picker to select a day. focus-trap prevents clicks inside Kendo picker, beacuse Kendo reparents its pickers directly under `<body>` element, so pickers are treated as outside elements by focus-trap.

To solve this problem I'm going to create PR with additional configuration option:

`includeOutsideElement: Function(element:HTMLElement):boolean ` a function which will be called when focus-trap detects click/mousedown/touchdown events outside trapped container. `true` result of this function will not prevents and not stops above events. Developer needs to prevent those events on his own handlers. Kendo prevents mousedown events inside pickers, so focus won't be lost.

**Comment by davidtheclark** [comment]
Hello @gejgalis. I have a question: When a DatePicker opens, shouldn't focus be able to enter that picker? If `includeOutsideElement` only *allows clicks* in the outside element, you can't get to the outside element by tabbing, right?

If you agree that we may want to allow focus to move between the elements (the original form and the displaced DatePicker), maybe the solution is to allow focus trap to accept multiple elements?

**Comment by gejgalis** [comment]
Hello @davidtheclark . Kendo pickers prevents mousedown event, so you can't jump with focus from date input to date picker - you can only use a mouse to choose a day, so focus always stays in date input.  [See date picker demo](https://demos.telerik.com/kendo-ui/datepicker/index)

Allowing multiple elements upfront as one logical trap container is not always possible (using HTMLElement reference), because some of those elements are created dynamically after click. It would be only possible by configuring string selector (not HTMLElement reference). If you are OK with that - it will work for me too.

**Comment by gejgalis** [comment]
@davidtheclark you want me to prepare PR for multiple targets?

**Comment by davidtheclark** [comment]
@gejgalis Sorry for the delayed answer here. If you're still interested in trying to add this feature, I'm open to a PR.

**Comment by davidtheclark** [comment]
This is certainly an edge case and nobody has yet finished a PR with a workable API. So I'm going to close this issue for now. If you are invested in this use case and want to work out the details with me, please open a new issue.
