### ISSUE TITLE
input.select() should not be called for already focused input fields

### ISSUE THREAD

**Issue by MichaelTamm** [davidtheclark/focus-trap#47]
Hi,

because of issue #3 the `tryFocus` function calls `node.select()` if `node` is an input field.

Unfortunately this destroys the current selection, if the input field is already focused.

Therefore I suggest to change the first line of the `tryFocus` function from:

    if (!node || !node.focus) return;

to:

    if (!node || !node.focus || node === document.activeElement) return;

This would prevent, that the selection of an already focused input field is destroyed.

**Comment by flundermicha** [comment]
Sorry, I just saw, that I was looking at an old version of focus-trap. This issue was already fixed with version 2.3.1

**Comment by davidtheclark** [comment]
@MichaelTamm I'm not sure I understand the problem. My understanding is that it's expected behavior that if you select text in an input then hit tab, you'll lose that selection. Would you mind providing a JSBin or something illustrating your point?

**Comment by MichaelTamm** [comment]
You can close the issue. It was fixed in version 2.3.1 when the line

    if (node === document.activeElement)  return;

was added to the `tryFocus` function.
