### ISSUE TITLE
Allow `initialFocus` to be false

### ISSUE THREAD

**Issue by heylookltsme** [davidtheclark/focus-trap#5]
It would be great if we could set `initialFocus` (or perhaps a new option) to `false` in order to keep focus on whatever element had it prior to the focus trap being activated. And then the next tab event would go to the first focusable element inside the trap. 

My use case is a header with several icons, each of which open a popover. When a popover opens, I want to set a focus trap on the popover element, but I want to keep focus on the icon in the header until tab is pressed again. Does that make sense? 

I might take a stab at implementing this myself if I have time.

**Comment by davidtheclark** [comment]
Yes, it makes sense.

To make sure we're on the same page: You can to open the popover, then if the user presses tab put focus in the popover and never have it return to the trigger until the popover closes? ---- i.e. the trigger is not part of the focus-group?

One consideration here: The ARIA description of a Dialog says "When a modal dialog opens focus goes to the first focusable item in the dialog." I also have the question of whether you want tab to go through the menu and not go to the next icon in the header, with up/down arrows going through the menu (possible with [focus-group](https://github.com/davidtheclark/focus-group))?

**Comment by heylookltsme** [comment]
Ahh I wasn't aware of either the ARIA spec that says this is how modal dialogs are supposed to behave or your focus-group module. That does seems like a better solution. Feel free to close this if you feel the feature should not be added to focus-trap. 

Thanks!

**Comment by davidtheclark** [comment]
Also, I added another demo that might help for your situation: http://davidtheclark.github.io/focus-trap/demo/#demo-four-heading. It shows how you could use `initialFocus` to pass focus to a container instead of the first regularly focusable node.
