### ISSUE TITLE
Focus trap breaks native radio form flow

### ISSUE THREAD

**Issue by doodirock** [davidtheclark/focus-trap#52]
Just ran into an issue using this on a project with modals that have a form with radio buttons.  The standard functionality for a radio button group is that when I tab into a radio form, it will focus in on the first unselected radio button in that group.  When I then press tab again, the focus should leave the radio group entirely and hit the next element (in this case a submit button).

However if the same form is within a modal with focus trap, I am then forced to focus on each individual radio button options within the radio group instead of skipping directly to the submit button on TAB.

This creates an inconsistent experience between forms and may lead to confusion for non-sighted users who rely on keyboard controls to navigate through a site.  

https://www.w3.org/TR/wai-aria-practices/#radiobutton

**Comment by davidtheclark** [comment]
Thanks, @doodirock. This actually goes back to the library tabbable. Tracking upstream: https://github.com/davidtheclark/tabbable/issues/28

Tough problem, open to solutions.
