### ISSUE TITLE
Focusing on first focus-able element by default is a major accessibility issue

### ISSUE THREAD

**Issue by Dan503** [davidtheclark/focus-trap#56]
I created a pull request for this issue here: https://github.com/davidtheclark/focus-trap/pull/55

The current implementation of focus-trap has a major accessibility issue that can easily be resolved by making the focus-trap container the default element that receives focus when the focus trap is activated.

For example, have a look at demo 1 on the [demo site](http://davidtheclark.github.io/focus-trap/demo/).

This is what the UX is like for a screen reader user using [NVDA](https://www.nvaccess.org/download/) trying to use demo 1 running the current focus-trap default implementation:

1. Focus on activate button
2. _"activate trap 1 [button]"_
2. Press enter
3. _"with [link]"_

Now this is what it is like if you accept my pull request:

1. Focus on activate button
2. _"activate trap 1 [button]"_
2. Press enter
3. _"Here is a focus trap with [link] some [link] focusable [link] parts. Deactivate trap 1"_

See how much more accessible this default functionality is for screen reader users?

**Comment by davidtheclark** [comment]
Thanks for the suggestion, @Dan503.

I don't think I'm convinced yet that this is the best default behavior for focus-trap. I believe you already  *can* accomplish it — focusing a container element — but in many cases it may *not* be desirable. 

For example, in [the WAI-ARIA Authoring Practices modal dialog description](https://w3c.github.io/aria-practices/#dialog_modal), they recommend first focusing an interactive element or title when a modal opens, not the modal's container element. 

You're right that in your example the verbosity seems helpful; but I'm not sure whether that's reflective of a realistic encounter a screen-reader user would have with a well-designed component. 

So, considering that this behavior should be possible now and those ARIA recommendations don't prescribe it in the most common focus-trapping situation (a modal), I'm inclined to think the current defaults are fine. Still open to more information, though.

**Comment by Dan503** [comment]
> but in many cases it may not be desirable.

Can you give an example?

**Comment by davidtheclark** [comment]
> the best possible accessibility for modal dialogues 

Unless I see more information to the contrary, I feel like I should trust the WAI-ARIA Authoring Practices to tell me what's accessible behavior for a modal dialog. And you haven't addressed your divergence from their recommendations. 

I believe there *is* some authoritative work in support of your suggestion, e.g. https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/. However, I find *more* suggestions in line with the WAI-ARIA Authoring Practices. If you can find more authoritative info, I'd be very interested. But maybe not for *this* library so much as for modal components ...

> We are talking default behaviour here so we are generally talking about implementation by devs who just want it to work and aren't thinking that much about accessibility.

That is not the concern of this library. It *can* be used in a universally accessible way (and ideally would be). But it doesn't have to be: for example, it could be used in a way that targets sighted keyboard users. focus-trap is not *endorsing* anything: it is a low-level utility library that other things can be built on top of. This isn't a modal component — it's mean *to be used by* modal components.

If you'd like to make a modal library that uses focus-trap in the way that you think is best, you should! Happy to link to it in the readme.

> Plus there is also the added benefit of the plugin not throwing an error if the user triggers a focus-trap on an element that has no tabbables inside of it.

I still don't think this is a benefit: that situation is a user error.

---

So: I think that if you'd like to propose an option to include the container in the focus trap, I'd be open to that. I'm not sure we need a significant, breaking change, though, to address concerns that may be more appropriately addressed in higher-order libraries.

**Comment by Dan503** [comment]
I've had a thought on how this can be implemented without causing a major breaking change to the plugin.

What if by default on activation, focus-trap also takes tabindex="-1" elements and it's container into consideration on where it sends it's initial focus to?

So if the user adds tabindex="-1" to the focus-trap container, then the container will receive focus by default. If a heading inside the container has tabindex="-1" then the heading will receive focus.

It should only take tabindex="-1" elements into consideration on initial focus. They should not be taken into consideration after inital focus.

To make this easier in this plugin, it would be good if there was an `includeNegatives` option in the [Tabbable](https://github.com/davidtheclark/tabbable) plugin.

This means that people can get the container focus functionality by default as long as they manually add the negative tabindex property to the focus-trap element themselves.

I don't think it is likely to break current implementations since it requires the user to explicitly add a negative tabindex in the HTML for it to change the functionality.

I'd prefer container focus to be the general default functionality but I don't see that happening. Would you be open to this as a solution?

**Comment by davidtheclark** [comment]
This is already possible, exemplified in the demo, and now mentioned in the docs, so I don't think changes are necessary. But thanks for the discussion.

**Comment by Dan503** [comment]
I don't see any warnings in the documentation about the potential accessibility issues that come from sending focus to the first focusable element.

There should at least be a warning somewhere to notify users of the potential issue.
