### ISSUE TITLE
FEATURE REQUEST: make it optional to interact with the mouse outside the focus-trap

### ISSUE THREAD

**Issue by PieterSwitten** [davidtheclark/focus-trap#63]
We want to keep de keyboard tabs within the focus-trap but when a notification pops up the user should be able to interact with the notification with the mouse. 

We don't have the need to have the clicks blocked outside the focus-trap. Would be nice if this is optional

**Comment by davidtheclark** [comment]
Hi @PieterSwitten. This has already been discussed a number of times, and there have been a few abandoned PRs. Please search the issues and PRs to find the backstory, then open a new issue if you have a new idea or a PR if you're able to implement something. Thanks.

**Comment by lambert-velir** [comment]
I have a dropdown component, which, when opened, will attach a "click away" listener to the document to close the dropdown when the user clicks outsides of the dropdown.  The FocusTrap seems to be blocking this click event from happening.  How can I implement this behavior without an option to disable the FocusTrap from interfering with the click events?

**Comment by lambert-velir** [comment]
I just did some more digging and found the `clickOutsideDeactivates` option, that works, nevermind!

```
<FocusTrap
  active={isOpen}
  focusTrapOptions={{ clickOutsideDeactivates: true }}
>
```
