### ISSUE TITLE
Thank you 💖

### ISSUE THREAD

**Issue by aaronransley** [davidtheclark/focus-trap#64]
This library has proved immensely helpful in adding more friendly screen reader UX to a recent web project. Thank you so much, David, for your work on `focus-trap` and `tabbable`. You may see a `focus-trap-vue` popping up soon enough if I can manage my time wisely!

All the best,
Aaron

**Comment by davidtheclark** [comment]
Thanks, @aaronransley! I really appreciate the kind words.
