### ISSUE TITLE
Not working inside another focus trap and custom elements

### ISSUE THREAD

**Issue by puranjayjain** [davidtheclark/focus-trap#7]
Hi I'm using the focus trap api to trap focus within a custom element where it works.

The code was coverted to coffescript for the project here https://github.com/puranjayjain/chrome-color-picker

However, when triggering the focus trap within another element within it the focus trap occurs on the new element and removes from the old element(as expected) but the focus is locked on one element inside it and won't change.

I tried changing the other element's tabindex to 0, 1, 2 but it won't change no matter what.

The relevant lines of code are
https://github.com/puranjayjain/chrome-color-picker/blob/master/lib/chrome-color-picker.coffee#L930

and other places in this file where the setTrap function was used

**Comment by puranjayjain** [comment]
this is the dom structure
```html
<ccp-container>
   bunch of tags
   <ccp-palette-popup tabindex="0">
        <ccp-panel>
           <h3>Color Palettes</h3>
           <button class="btn btn-error btn-sm icon icon-x"></button>
        </ccp-panel>
        <ccp-panel class="material" tabindex="1">
             <div>Material</div>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
        </ccp-panel>
        <ccp-panel class="custom" tabindex="1">
             <div>Custom</div>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
             <ccp-swatch class="square"></ccp-swatch>
        </ccp-panel>
    </ccp-palette-popup>
</ccp-container>
```

the error happens in the last of these steps:
- the focus trap is set on `ccp-container`, `ccp-palette-popup` is invisible using `display: none`
- the focus trap is now set to `ccp-palette-popup`
- the initial focus is `ccp-panel.material`
- the focus is fixed on it and doesn't change from it

This happens in atom (which runs on chromium v47)

**Comment by davidtheclark** [comment]
Open to a PR fixing this.

**Comment by puranjayjain** [comment]
@davidtheclark I'll dive into the source most probably next week. :construction:

**Comment by davidtheclark** [comment]
Should be fixed in v2.

**Comment by davidtheclark** [comment]
@puranjayjain When you try this again, have a look at demo-six.

**Comment by puranjayjain** [comment]
Thank you :smile:
