### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by designjockey** [davidtheclark/focus-trap#71]
Could you please add release notes when you create releases? It makes it easier for consumers to update the dependency in a more informed way if they can read the release notes.

**Comment by davidtheclark** [comment]
@designjockey We have a [CHANGELOG.md](https://github.com/davidtheclark/focus-trap/blob/master/CHANGELOG.md).

**Comment by dwightjack** [comment]
@davidtheclark thanks for your work!

Just noticed that npm reports a 4.0.0 version but this github repository changelog and releases do not seem to contain any reference to that release.

Am I missing something?

**Comment by davidtheclark** [comment]
Thanks @dwightjack. I did forget to push the commit that added 4.0.0 info to the changelog! That commit is in the GitHub repo now.
