### ISSUE TITLE
Create a new release that includes PR #69 changes.

### ISSUE THREAD

**Issue by alexanderjeurissen** [davidtheclark/focus-trap#73]
As mentioned in  https://github.com/material-components/material-components-web/issues/4104 we need the change referenced in https://github.com/davidtheclark/focus-trap/pull/69 in order for `material-components-web` and `material-components-web-react` to correctly render the drawer when server side rendering react components.

As such I wanted to inquire if we can create a new release that contains said PR that has been merged in ~1 month ago. That way `material-components-web` can update their package.json, and `material-components-web-react` as well.

Thanks for your understanding, let me know If there is anything I can do to help get this done.

**Comment by davidtheclark** [comment]
v4.0.0 should include that dependency update. I just realized it was missing from the GitHub releases page — sorry, fixed now — maybe that led you to think there were no more recent releases.

**Comment by alexanderjeurissen** [comment]
Ah that makes sense, apologies I didn't check NPM and assumed based on the github releases that no new release was created. Thanks for coming back to me on this.
