### ISSUE TITLE
function createFocusTrap is undefined

### ISSUE THREAD

**Issue by mrleblanc101** [davidtheclark/focus-trap#74]
Hi,
Shouldn't it be ```trap = focusTrap();``` ? 
Instead of ```trap = createFocusTrap()```

**Comment by davidtheclark** [comment]
I don't understand the issue here, @mrleblanc101. If that's how you'd like to name things in your code, you can do that: `const focusTrap = require('focus-trap'); const trap = focusTrap();`.

Please re-open with more information if that isn't what you're referring to.
