### ISSUE TITLE
Activating a trap updates the tabbable nodes twice

### ISSUE THREAD

**Issue by stof** [davidtheclark/focus-trap#76]
In my experience, the bottleneck of activating a focus-trap is the tabbable library when the trap contains lots of tabbable nodes.
When activating a trap, the list of tabbable nodes is updated twice: one directly in `activate` and one inside `addListeners`. Would it be possible to combine those to update the list only once ?

**Comment by stof** [comment]
For reference, in a case of a MDC Dialog (which uses focus-trap) containing a thousand of checkboxes in it, I got timing of ~900ms for each call to `updateTabbableNodes` in `activate`. That's why I'm thinking it might be worth updating the list only once if that does not break things (AFAICT, only the `onActivate` callback runs between them)

**Comment by davidtheclark** [comment]
Hi @stof. I'd welcome a change that makes this more efficient. The challenge here is to minimize the tabbable checks while still allowing focus-traps to be paused and reactivated, and to pick up on DOM changes within the trap.

**Comment by stof** [comment]
@davidtheclark is it a supported use case to change the list of tabbable nodes inside a `onActivate` callback ? Or can we assume that the list will not change in the callback ?

**Comment by davidtheclark** [comment]
I don't think that's a use case that we need to support.
