### ISSUE TITLE
Allow custom keys

### ISSUE THREAD

**Issue by yotamDvir** [davidtheclark/focus-trap#8]
Should [`tab`](https://github.com/davidtheclark/focus-trap/blob/master/index.js#L97-L100) and [`escape`](https://github.com/davidtheclark/focus-trap/blob/master/index.js#L140-L142) keys be configurable? Example use case would be to allow the use of `up` and `down` keys instead of `tab` and `shift-tab`.

**Comment by davidtheclark** [comment]
Doesn't sound to me like a "focus trap" if you can tab out of it. Right? 

Would https://github.com/davidtheclark/focus-group fit your purposes?

**Comment by yotamDvir** [comment]
I wasn't suggesting tabbing out would be possible, you could either (a) leave `tab` key operating and just add the `up` key as another possible key, or (b) disable `tab` from working when not including it in the custom configuration.
My specific use case is creating an online test that is mostly about copying stuff into a form accurately. I would like the user to be able to move between the fields using the arrow keys as well as tab. I would still like the user to be trapped in the form.
Exposing an API call for specifying desired keycodes for each action would suffice, but you could possibly delegate to another library, like [KeyboardJS](https://github.com/RobertWHurst/KeyboardJS).
Would definitely understand if you don't like this proposal for this library, I merely suggest it since I have a use case for it and I believe others may as well.

**Comment by davidtheclark** [comment]
Did you look into focus-group? I think that does what you want.

**Comment by yotamDvir** [comment]
Implementing my specific need myself turned out to be simpler. Thanks anyway!
