### ISSUE TITLE
Trap Focus for nested Modals isn't working

### ISSUE THREAD

**Issue by knoefel** [davidtheclark/focus-trap#9]
Let's assume you have two nested modals. When you open the first modal, the second inner modal is hidden at this time. Until then everything works just fine with your focus trap implementation. But when you open the second inner modal the following error message appears: 

> Uncaught Error: You can't have a focus-trap without at least one focusable element"

The problem is that you cache the display state of all tabbable elements and their parents inside your dependency 'tabbable'. So when i first run the `focusTrap.activate` method on the outer modal, the display state for all tabbable elements of the inner modal are set to hidden.

My current workaround is to delete the property 'tabbableCacheIndex' on the related tabbable elements and their parents before i run the `focusTrap.activate` method the second time. 
I really like to use your 'focus-trap' - module so let me know if i could help.

**Comment by davidtheclark** [comment]
Is this the same as #7?

**Comment by davidtheclark** [comment]
I think I found a fix in 414b1630573552a7f162f283ab118c044a63e336. If you can try out master and let me know if that works for you, I'd appreciate it.

**Comment by davidtheclark** [comment]
Should be fixed in v2.

**Comment by knoefel** [comment]
Sorry for the late reply. Thank you so much for your really quick fix. I've tested the 2.0.1 version and everything is working fine!!!

**Comment by davidtheclark** [comment]
Fantastic.
