### ISSUE TITLE
allowOutsideClick boolean

### ISSUE THREAD

**Issue by SassNinja** [davidtheclark/focus-trap#90]
Hi,

I wanna close my trapped element when the user clicks outside.
So those clicks shouldn't get prevented by this module.
The only way I've found was using `allowOutsideClick` and simply always return true.

```javascript
trap = focusTrap(elem, {
    initialFocus: elem,
    allowOutsideClick: () => true
});
```

Seeing this I'd like to simply replace that function with a boolean.
What do you think about adding boolean support here?
Or is there any other way I've missed?

**Comment by jtomaszewski** [comment]
I think doing `() => true` is good enough here. No need to add support for booleans.
